### ISSUE TITLE
AR Foundation 4 shows warning: "No active UnityEngine.XR.XRInputSubsystem is available. Please ensure that a valid loader configuration exists in the XR project settings.

### ISSUE THREAD

**Issue by marwie** [needle-tools/ar-simulation#1]
```UnityEngine.XR.ARFoundation.ARInputManager:OnEnable() (at Library/PackageCache/com.unity.xr.arfoundation@4.0.0-preview.3/Runtime/AR/ARInputManager.cs:23)"```

**Comment by marwie** [comment]
Question has been asked in forum: https://forum.unity.com/threads/why-is-no-xrinputsubsystem-registered.947448/

**Comment by daltonbr** [comment]
Got this warning about `XRInputSubstystem` missing, as well as the `XROcclusionSubsystem`. I am using AROcclusionManager.

```No active UnityEngine.XR.ARSubsystems.XROcclusionSubsystem is available. Please ensure that a valid loader configuration exists in the XR project settings.
UnityEngine.XR.ARFoundation.SubsystemLifecycleManager`2:OnEnable() (at Library/PackageCache/com.unity.xr.arfoundation@4.1.0-preview.6/Runtime/AR/SubsystemLifecycleManager.cs:87)
```

**Comment by marwie** [comment]
Yes, we don't have support for AROcclusion right now. I'm currently trying to get QA to "reproduce" it, you can follow progress here http://fogbugz.unity3d.com/default.asp?1268913_ib36qa30bbobpvuf

**Comment by marwie** [comment]
The issue has been reproduced
https://issuetracker.unity3d.com/product/unity/issues/guid/1268913

**Comment by marwie** [comment]
Closing because it is an expected warning. In editor we dont register a XRSubsystem rigth now, because that can only be done with an unmanaged plugin. Right now there is no need for this and it will only introduce complexity and potential bugs.
