### ISSUE TITLE
AR Foundation - Long clicking when placing an object seems to offset its position

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/ar-simulation#25]
**Describe the bug**
 Long clicking when placing an object seems to offset its position, it keeps moving while you hold the click down but keep the cursor still - see video

**Steps to reproduce the behavior**
1.Using arfoundation samples - open Scenes > SimpleAR > SimpleAR
2. Hit play mode and keep the left click button down when placing an object

**Expected behavior**

Object should be placed and stay still with the mouse if it isn't moving

**Actual behavior**

Object keeps moving in a forward-ish direction even though the mouse is kept still.

**Screenshots / GIFs**
[video](https://drive.google.com/file/d/1aZlNXeLlafufVGY7RxoKM82MQU75wQBV/view?usp=sharing)

**Versions (please complete the following information):**
 - Unity [2020.2.0a13]
 - ARFoundation [e.g. 4.0]
 - OS: [Windows 10]
 - ARSimulation [e.g. 1.0.0 - preview 4]

**Comment by marwie** [comment]
Did not reproduce in 2019.3f15.
Opening in 2020.2.0a11 now while waiting for 13 and 15 (latest) to install

**Comment by marwie** [comment]
Tried the scene in both a13 and a15 left clicking at different camera angles and movements but could not reproduce the error unfortunately. Not sure what caused the issue there.

**Comment by ROBYER1** [comment]
I can try to send you a repro project of it tomorrow if you like?

**Comment by marwie** [comment]
That'd be great, thank you :)

**Comment by ROBYER1** [comment]
Got your repro project here, if you need anything else let me know [Link](https://drive.google.com/file/d/1oG9IJxKFhMEgUxTg9EZg_nuczNqHfBk0/view?usp=sharing)

**Comment by marwie** [comment]
Hello Robert, I just tried reproducing the bug with your project again (thank you!!!) in a13 and a15 but wasnt able to reproduce the error :/ 
Does this bug still happen if you open the project again? Maybe without the mouse input overlay?

**Comment by ROBYER1** [comment]
Hi Marcel, I checked again before zipping up the project that the long-click bug happened and once again just now it still occurs
