### ISSUE TITLE
AR Foundation - Holding right click, moving then clicking left produces an error

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/ar-simulation#26]
**Describe the bug**

Holding  right click, moving the cursor then clicking with left click produces an   error 'transform.position assign attempt for 'AR Camera' is not valid'

Error: `
transform.position   assign attempt for 'AR Camera' is not valid. Input position is { NaN, NaN,   NaN }.     UnityEngine.Transform:set_position (UnityEngine.Vector3)     Needle.XR.ARSimulation.Simulation.DesktopPoseProvider:LateUpdate () (at   Library/PackageCache/com.needle.xr.arsimulation@1.0.0-preview.3/Runtime/InputDevices/DesktopPoseProvider.cs:128)`

**Steps to reproduce the behavior**
1.Using arfoundation samples - open Scenes > SimpleAR > SimpleAR
2. hit play and hold down right click then move the cursor and left click
refer to video if unsure

**Expected behavior**

Should be no error message

**Actual behavior**

Error message, that never goes away in play mode!

**Screenshots / GIFs**

[Video](https://drive.google.com/file/d/1cHg2v5SaR-1VxkP6AaCe26g0Rpmf_wfH/view?usp=sharing) 

**Versions (please complete the following information):**
 - Unity [2020.2.0a13]
 - ARFoundation [e.g. 4.0]
 - OS: [Windows 10]
 - ARSimulation [e.g. 1.0.0 - preview 4]

**Comment by marwie** [comment]
Thanks for the report! I found the issue and it should be fixed in the next update :smiley:
