### ISSUE TITLE
Automatic enabling in XR Management does not work when XR Management has never been initialized

### ISSUE THREAD

**Issue by marwie** [needle-tools/ar-simulation#28]
**Describe the bug**
When installing AR Simulation to a fresh project it should enable itself in XR Plug in Management automatically by default. This does not work though because XR plugin management only initialized when the settings window gets opened (creating necessary scriptable objects and hooking everything up for the first time).

**Steps to reproduce the behavior**
1) create a new project with e.g. 2019.3
2) drag drop the ar simulation installer package in project
3) wait for installation to finish
4) Note: no XR folder/ missing ``XR/XRGeneralSettings`` in Assets and no log message about "XR Loader has been enabled"
5) open a sample scene and enter play mode
6) Node: warnings in console about no XR Subsystem being available
7) leave play mode
8) open Project Settings and select "XR Plug in Management"
9) Note: XR folder with XR General Settings in Assets gets created 

**Versions (please complete the following information):**
 - Unity 2019.3.15
 - AR Simulation Installer 1.0.0-preview.5

**Comment by hybridherbst** [comment]
I don't really think this is an issue. If a project hasn't been set up for XR yet at all (so, also not for ARCore/ARKit) then there's no expectation/not our responsibility to do that. We can warn about this on install, but I wouldn't enforce anything here.

**Comment by marwie** [comment]
By opening ``Project Settings/XR Plug in Management" once on installation (if not setup at all) that issue fixes itself (this would have been done by the user anyways, otherwise there is no reason to install the package). 
It is quite an edge case anyways. Alternativelly we could just warn. Sure.
