### ISSUE TITLE
Toggling "Is Active" on Simulated AR Environment multiple times doesn't work

### ISSUE THREAD

**Issue by hybridherbst** [needle-tools/ar-simulation#30]
**Describe the bug**

Toggling "Is Active" on Simulated AR Environment multiple times doesn't work.

**Screenshots / GIFs**
![20200628-010909](https://user-images.githubusercontent.com/2693840/85933912-8c09f480-b8dc-11ea-8da2-e8bb92813ca5.gif)
(difficult to see: in the end I'm trying to click on "Is Active")

**Versions (please complete the following information):**
 - ARSimulation [1.0.0-preview.7]

**Comment by marwie** [comment]
Will be fixed in 1.0.3
