### ISSUE TITLE
[Customer Reported] SimulatedARPoseProvider receives WASD inputs even when input fields are focussed

### ISSUE THREAD

**Issue by hybridherbst** [needle-tools/ar-simulation#41]
**Describe the bug**
There was a confusing case where the AR camera appeared at a seemingly random place when activating AR (AR was not active from the start of the experience).
The underlying issue seems to have been that when entering some text in the app, the camera was moved by WASD key presses. This probably shouldn't happen when any input field has focus.

**Expected behavior**
Camera doesn't move when text is entered into an Input Field

**Actual behavior**
Camera moves around

**Comment by marwie** [comment]
Should be fixed the next version

**Comment by marwie** [comment]
Release in version 1.0.5
