### ISSUE TITLE
Where is ARmeshmanager example scene

### ISSUE THREAD

**Issue by orangeagain** [needle-tools/ar-simulation#43]
This plugin is cool.but I can't find ARmeshmanager example scene now.can anyone know where is it?

**Comment by marwie** [comment]
Hi, thank you
Which version are you using?
You can install the meshing sample from PackageManager/ARSimulation and then at the bottom should be two samples: getting started and meshing

**Comment by orangeagain** [comment]
> Hi, thank you
> Which version are you using?
> You can install the meshing sample from PackageManager/ARSimulation and then at the bottom should be two samples: getting started and meshing

ARSimulation didn't show in PackageManager

**Comment by marwie** [comment]
How did you install it?
Have you tried enabling preview packages?
Is the dropdown in packagemanager at the top left set to "In Project"? (Not Unity Registry or Assets)

**Comment by orangeagain** [comment]
> How did you install it?
> Have you tried enabling preview packages?
> Is the dropdown in packagemanager at the top left set to "In Project"? (Not Unity Registry or Assets)

In project didn't show too.

**Comment by marwie** [comment]
@orangeagain did you find it?

**Comment by orangeagain** [comment]
no, I use arfoundation remote😓
