### ISSUE TITLE
[Package Manager] Failed getting latest version for AR Simulation

### ISSUE THREAD

**Issue by puos** [needle-tools/ar-simulation#46]
Hi~
This is happening in my laptop wifi environment. I don't know why, but  ㅠㅠ
Maybe it is related to wifi. Or maybe my location is related to Korea.
I confirmed that it works in other desktop environments. I hope this helps.

![image](https://user-images.githubusercontent.com/37793103/105089621-b6253d00-5ae0-11eb-903a-9e0cfc7e85a5.png)

**Versions (please complete the following information):**
 - Unity 2019.4.9f1
 - ARFoundation 4.1.1
 - Windows 10  HP Notebook

**Comment by hybridherbst** [comment]
Hi, 
thanks for reporting!
Are you able to manually add ARSimulation as package to package manager, not using the installer?

Also, I think the Unity version you're using there (2019.4.9) had some issues PackMan resolve (what you're seeing); might be worth testing on a later 2019.4 version but you might be right that this is a network/ISP issue.

**Comment by puos** [comment]
Thank you for your care ^^
We still have this problem and we will send you the Editor log of Unity.
[Editor.log](https://github.com/needle-tools/ar-simulation/files/5935995/Editor.log)

**Comment by marwie** [comment]
Mmmh the log says Unity cannot connect to the local package manager. Can you install any package via Unity PackageManager (Window/PackageManager) ?

`` [Package Manager] Server::Start -- Port 55597 was selected
[Package Manager] Cannot connect to Unity Package Manager local server
``

**Comment by marwie** [comment]
Here is another thing you could try. 
Modify the manifest.json in the ``Packages`` folder to add ARSimulation:

![image](https://user-images.githubusercontent.com/5083203/107103502-30aec600-681e-11eb-9100-c2f228694ae3.png)

```
{
  "scopedRegistries": [
    {
      "name": "needle",
      "url": "https://packages.needle.tools",
      "scopes": [
        "com.needle"
      ]
    }
  ],
  "dependencies": {
    "com.needle.xr.arsimulation": "1.2.0-preview",
....
```

Let me know if it helps!

**Comment by marwie** [comment]
If not you can download this version from here:
https://packages.needle.tools/com.needle.xr.arsimulation/-/com.needle.xr.arsimulation-1.2.0-preview.tgz

BUT the downside is: you will not be able to get updates via package manager or asset store so it would really be best if you find a way to use the PackageManager :)

**Comment by hybridherbst** [comment]
One more idea, does this happen to be on a machine with processor being either
i7-1065G7, i5-1035G4, i7-1035G7 or something similar? 

If yes, you might be hitting a very arcane bug that Unity only fixed recently on 2020.2.3f1, 2019.4.19f1, 2021.1.0b4 that prevented packages from custom registries to be used in some cases. Might be worth updating in case you have one of those processors.

**Comment by marwie** [comment]
Hello @puos, any news on this?

**Comment by marwie** [comment]
Hello @puos is this still a problem for you? Do you use any of the processors mentioned by @hybridherbst above?
