### ISSUE TITLE
Unable to navigate using right mouse + keyboard combination

### ISSUE THREAD

**Issue by jBachalo** [needle-tools/ar-simulation#47]
**Describe the bug**
Everything works except for navigation within the simulated AR scenes.
ie Right Mouse Button and WASDQE.

This is for both Walk and Fly modes. Also applies to Focus. No keypress results in focus either at mouse position or screen center.

If this can be resolved will definitely purchase.
Unity 2020.20b14 Windows.
AR Foundation  and ARKit 4.1

**Comment by marwie** [comment]
Hello, is this happening in Device Simulator or Game View (or both?) 
Could you check if in playmode the bool "Simulate Touch" is enabled on InputHelper (a component added to the main camera)? If yes try disabling it and let me know if that helped

**Comment by jBachalo** [comment]
Ok so maybe my lack of understanding in proper use. Only happens in Device Simulator.
With AR Simulator your are supposed to be only using Game View? Don't think this was made clear in instructions.

**Comment by marwie** [comment]
No it is supposed to work in Device Simulator as well. I'll have to look into it. 
Which version of AR Simulation are you using?

**Comment by jBachalo** [comment]
1.0.5

**Comment by jBachalo** [comment]
But other than the device 'chrome' is the simulated functionality is the same in Game View?

**Comment by marwie** [comment]
Could you please try updating to ``1.1.0-preview.5`` and check if it is fixed? I fixed an issue relating to Device Simulator input not working properly in one of these updates

**Comment by jBachalo** [comment]
Thanks will do. Also in Game view I still cannot move, only orbit with right mouse click and focus with F key. Will try the update.

**Comment by marwie** [comment]
Ok let me know if it helps. It might be possible that game view does not work as well if device simulator is broken and open (or if you're using the gameview dropdown from the device simulator instead of the regular game view window). But I hope it works with the newest version :)

**Comment by jBachalo** [comment]
So relaunched after deleting my Library.
What does work now is keyboard movement in Game View without keypress. However Simulation View still seems broken in terms of movement and focus with keypress+right mouse click.

Might have something to do with my combination of bluetooth mouse+keyboard and or Unity version. Don't have time to further troubleshoot at the moment.

**Comment by marwie** [comment]
I'm using bluetooth as well here. I'll try to reproduce it later and let you know how it goes

**Comment by marwie** [comment]
Oh I forgot to ask: which Device Simulator version are you using?

**Comment by marwie** [comment]
So 2020.2.2f1 with Device Simulator 2.2.4-preview worked for me. I used ``Tools/AR Simulation/Convert to Extended AR Scene`` for testing.
These are my input settings:
![image](https://user-images.githubusercontent.com/5083203/106494538-d8dd2b80-64ba-11eb-99d5-21b360961ede.png)

Let me know which device simulator version, exact editor version and your input settings you're using. 
Do you have any specific reasion why you're using a Unity beta version? If possible try updating both the editor and the device simulator package.
If none of the above helps or is possible do you think you could send me a project to debug?

**Comment by jBachalo** [comment]
Same versions.
Might have found the issue however. On my input settings for Mouse I cannot select just
Require Right Mouse Pressed to Move
Its either Nothing or Everything.

ie if I try to select only 'Require Right Mouse Pressed to Move' it always defaults to everything.
The drop down then shows both 'Everything' AND 'Require Right Mouse Pressed to Move' selected.

**Comment by marwie** [comment]
That's not the reason unfortunately (Everything is correct because ``Require Right Mouse Pressed`` is the only option so it displays it like that)

It must be something else. Do you think you could send me a minimal version of a project where input does not work as expected for you?

**Comment by marwie** [comment]
Hello @jBachalo did you find a solution?
