### ISSUE TITLE
Issue with scene setup / plane detection

### ISSUE THREAD

**Issue by kjyv** [needle-tools/ar-simulation#50]
The Readme mentions a SimulatedReality component which seems to allow a gradual plane detection from the simulated point cloud as it would appear on device. Does that feature not exist anymore?

**Comment by marwie** [comment]
Hello,

that's a mistake in the readme. The component the readme refers to is ``SimulatedEnvironment`` but its usecase is to just enable camera image rendering (or rather mark gameobjects and prefabs to be rendered as a background image).

For plane detection you can use the ``Simulated AR Plane Generation`` component

**Comment by kjyv** [comment]
Ok, so if I add Simulated AR Plane Generation to say a ground object, it should start detecting that as a plane? Somehow nothing happens. I have added a Simulated AR Plane component to it and the plane is detected right away (without the camera looking at it).

**Comment by marwie** [comment]
The simulated AR plane component will inject a rectangular plane when enabled. What you want is a ``Simulated AR Plane Generation`` component.
You can import the ARSimulation Getting Started samples. It contains some examples (Open via Window/ARSimulation)

**Comment by marwie** [comment]
See attatched video:
https://user-images.githubusercontent.com/5083203/109316095-90135b00-784b-11eb-85ad-57d089a4b5f9.mp4

![image](https://user-images.githubusercontent.com/5083203/109316138-9b668680-784b-11eb-8ed0-5eae0565b769.png)

**Comment by kjyv** [comment]
Yes yes, I've tried that, simply adding that component to our ground plane does not trigger plane detection. Anything else that needs to be done? We have Auto Scene setup disabled, could this be the reason?

**Comment by kjyv** [comment]
Alright, sorry for misusing the bug report about the Readme for all these support questions. Using the menu item "Convert to Extended AR Scene" and removing the Simulated Pose we can do what we want.

**Comment by marwie** [comment]
That's alright. Glad you got it working!

So the issue was that you had an additional Simulated Pose component (from ARSimulation) on the camera somehow?

**Comment by kjyv** [comment]
No, not somehow.  I deleted the one that "Convert to Extended AR Scene" creates. Basically that's the manual alternative to Auto Scene Setup I suppose.

**Comment by kjyv** [comment]
The other issue was actually that we didn't have a matching Layer set in Plane Generation, Planes are generated now.

**Comment by marwie** [comment]
> No, not somehow. I deleted the one that "Convert to Extended AR Scene" creates. Basically that's the manual alternative to Auto Scene Setup I suppose. I guess you could also have second option under Auto Scene Setup "Enable AR Controls" and we could disable that instead.

I think
