### ISSUE TITLE
Point clouds are saved in scene file

### ISSUE THREAD

**Issue by kjyv** [needle-tools/ar-simulation#52]
**Describe the bug**
When using the AR Point Cloud component, generated point cloud data is saved to the scene file and thus repeatedly shows up in our version control system (and has to be discarded). As it is no persistent information it should probably not be a SerializedField (or just not persist after play mode).

**Steps to reproduce the behavior**
Don't use Auto Scene Setup (but Auto Point Cloud is enabled),
but use manual setup via Tools -> AR Simulation -> Convert To Extended AR Scene

**Versions (please complete the following information):**
 - Unity 2019.4.22f
 - ARFoundation 4.1.5
 - OS: macOS 11.2.3
 - ARSimulation 1.2.0-preview.4

**Comment by marwie** [comment]
Hello @kjyv sorry for the delay. The points array is no longer serialized in ``1.3.0-pre.2``

**Comment by kjyv** [comment]
Looking good, thanks
