### ISSUE TITLE
Simulated environment textures get included in builds for IOS/Android

### ISSUE THREAD

**Issue by ROBYER1** [needle-tools/ar-simulation#55]
**Describe the bug**
Simulated environment textures get included in builds for IOS/Android

From the build log:
<img width="784" alt="Screenshot 2021-05-20 at 10 18 48" src="https://user-images.githubusercontent.com/10745594/118953612-e547a000-b954-11eb-960e-25d29b1efc2a.png">

**Steps to reproduce the behavior**
1. Import ARSim to a project for android/ios
2. Add a simulated environment manager to the scene, use the apartment scene for example
3. Activate the environment in the scene (see the instances appear)
4. Build the scene for IOS/Android, check the build log to see the environment textures are included

**Expected behavior**
Anything from ARSim should be excluded from the build as it adds 50mb+ to the builds

**Actual behavior**
Environment Simulation assets get included in builds

**Versions (please complete the following information):**
 - Unity  2020.3.6f1
 - ARFoundation 4.1.7
 - OS: Editor: MacOS Big Sur, Windows 10, build: Android/IOS
 - ARSimulation 1.3.0-pre.3

**Comment by marwie** [comment]
For future reference: issue was ``SimulatedEnvironmentManager`` gameobject was not tagged with ``EditorOnly`` tag
