### ISSUE TITLE
Rotation of ARPlanes is not considered in hitPose

### ISSUE THREAD

**Issue by EVOsparkLP** [needle-tools/ar-simulation#60]
**Describe the bug**
When raycasting on planes the rotation of the hit pose is always the same - no matter if horizontal or vertical planes are hit.

**Steps to reproduce the behavior**
1. Open example scene 'RaycastPlanesWithCameraImage'.
2. Move around to find planes on the floor and on the wall.
3. Raycast to the detected planes on the floor and on the wall.
4. Sample objects are placed on the floor and on the wall.

**Expected behavior**
The object which is placed on the wall should be rotated by 90 degrees as it is placed on a vertical plane. The "up-direction" of the placed object should match the plane's normal direction.

**Actual behavior**
Objects on the floor and on the wall are placed with the same rotation. The rotation is taken from the hitPose.rotation which means, that the hitPose does not consider the orientation of the plane. This differs from the behavior of the ARFoundation raycasting in real environments where the hitPose.rotation considers the plane rotation.

**Screenshots / GIFs**
![image](https://user-images.githubusercontent.com/79313352/173340097-d316bd34-a3e3-4efc-9296-61416b1417ec.png)
Screenshot shows that the objects placed on the horizontal and vertical AR plane have the same rotation. The object placed on the wall should be rotated by 90° to have the same behavior as in a real "non-simulated" environment.

**Versions:**
 - Unity 2020.3.34f1
 - ARFoundation 4.1.9 
 - ARSimulation 1.3.6
 - Device Simulator 3.0.3

**Comment by marwie** [comment]
Hello, thanks for the report! Seems like the rotation is calculated wrongly in some circumstances. I'll take a look

**Comment by marwie** [comment]
Ok I think I've found the cause and a fix

![image](https://user-images.githubusercontent.com/5083203/173344453-bd288309-8c50-46d9-991f-de854f005a98.png)

**Comment by marwie** [comment]
@EVOsparkLP please try version ``1.3.7`` that I've just published

**Comment by EVOsparkLP** [comment]
Wow, that was fast! The new version works perfect. Thanks for your support!

**Comment by marwie** [comment]
Great, good to hear
